export default {
  translation: {
    app_title: "Tracker",
    home: "Home",
    about: "About",
    features: "Features",
    faq: "FAQ",
    download: "Download",
    submit: "Submit",
    home_title: "Lorem ipsum dolor",
    home_p:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam explicabo, sapiente provident quam pariatur officiis non, alias neque ullam harum facere adipisci rerum numquam, aliquid ad id possimus illum! Perspiciatis!",
    welcome: "WELCOME TO HEALTH TRACKER",
    about_h: "HELLO! HEALTH CARE IS A NATURAL WAY OF IMPROVING YOUR HEALTH",
    about_p:
      "A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.",
    whychooseus: "Why Choose Us?",
    whychooseus_p:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequuntur sint similique reprehenderit quam ex libero accusantium doloribus veritatis corrupti, saepe nihil! Est nobis deserunt officia eligendi incidunt magni asperiores delectus!",
    feature_1: "Lorem ipsum",
    feature_body_1:
      "Lorem ipsum dolor sit amet placerat facilisis felis mi in tempus eleifend pellentesque natoque etiam.",
    feature_2: "Lorem ipsum",
    feature_body_2:
      "Lorem ipsum dolor sit amet placerat facilisis felis mi in tempus eleifend pellentesque natoque etiam.",
    feature_3: "Lorem ipsum",
    feature_body_3:
      "Lorem ipsum dolor sit amet placerat facilisis felis mi in tempus eleifend pellentesque natoque etiam.",
    feature_4: "Lorem ipsum",
    feature_body_4:
      "Lorem ipsum dolor sit amet placerat facilisis felis mi in tempus eleifend pellentesque natoque etiam.",
    q_1: "question",
    a_1: "answer",
    q_2: "question",
    a_2: "answer",
    q_3: "question",
    a_3: "answer",
    q_4: "question",
    a_4: "answer",
    q_5: "question",
    a_5: "answer",
    q_6: "question",
    a_6: "answer",
    q_7: "question",
    a_7: "answer",
    q_8: "question",
    a_8: "answer",
    testimons: "testimons",
    happy_client: "HAPPY CLIENTS & FEEDBACKS",
    feedback_1: "Lorem ispum dolor, sit amet consectetur adipisicing elit",
    client_1: "henry cavill",
    app_gallery: "App Gallery",
    ios: "IOS",
    android: "Android",
    our_plan: "our plan",
    plan_1: "dolor sit amet consectetur",
    plan_2: "dolor sit amet consectetur",
    plan_3: "dolor sit amet consectetur",
    plan_4: "dolor sit amet consectetur",
    iqd: "iqd",
    month: "month",
    get_started: "get started",
    footer_p:
      "A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.",
    usefull_links: "links",
    have_questions: "Have any Questions?",
  },
};
