export default {
  translation: {
    app_title: "تراکەر",
    home: "سەرەتا",
    about: "دەربارە",
    features: "تایبەتمەندییەکان",
    faq: "پرسیاری دووبارە",
    download: "ئێستا دایبەزێنە",
    home_title: "تەندروستییەکی باشتر و هێزی زیاتر",
    home_p:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam explicabo, sapiente provident quam pariatur officiis non, alias neque ullam harum facere adipisci rerum numquam, aliquid ad id possimus illum! Perspiciatis!",
    welcome: "بەخێربێن بۆ چاودێری تەندوستی",
    about_h: "تراکەر، ڕێگایەکی تەندروست و سروشتی بۆ تەندروستییەکی باشتر",
    about_p:
      "A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.",
    whychooseus: "بۆچی تراکەر؟",
    whychooseus_p:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequuntur sint similique reprehenderit quam ex libero accusantium doloribus veritatis corrupti, saepe nihil! Est nobis deserunt officia eligendi incidunt magni asperiores delectus!",
      features_p:'تراکەر بناسەوە بەهۆی دڵنیایی و پابەندبوون بە بنەماکانی توێژینەوەی زانستی و تەندروستی',
      feature_1: "زیاتر لە 1000 جۆر خواردن و خواردنەوە",
    feature_body_1:
      "Lorem ipsum dolor sit amet placerat facilisis felis mi in tempus eleifend pellentesque natoque etiam.",
    feature_2: "پلانی تایبەت بۆ رۆژووگران",
    feature_body_2:
      "Lorem ipsum dolor sit amet placerat facilisis felis mi in tempus eleifend pellentesque natoque etiam.",
    feature_3: "چاودێری بەردەوامی خواردن و خواردنەوە",
    feature_body_3:
      "Lorem ipsum dolor sit amet placerat facilisis felis mi in tempus eleifend pellentesque natoque etiam.",
    feature_4: "پابەند بوون بە بناماکانی تەندروستی",
    feature_body_4:
      "Lorem ipsum dolor sit amet placerat facilisis felis mi in tempus eleifend pellentesque natoque etiam.",
    q_1: "پرسیار",
    a_1: "وەڵام",
    q_2: "پرسیار",
    a_2: "وەڵام",
    q_3: "پرسیار",
    a_3: "وەڵام",
    q_4: "پرسیار",
    a_4: "وەڵام",
    q_5: "پرسیار",
    a_5: "وەڵام",
    q_6: "پرسیار",
    a_6: "وەڵام",
    q_7: "پرسیار",
    a_7: "وەڵام",
    q_8: "پرسیار",
    a_8: "وەڵام",
    testimons: "گەواهییەکان",
    happy_client: "دڵخۆشی و کاردانەوەی بەکارهێنەران",
    feedback_1: "Lorem ispum dolor, sit amet consectetur adipisicing elit",
    client_1: "henry cavill",
    app_gallery: "ئەپ گەلەری",
    ios: "ئای ئۆ ئێس",
    android: "ئەندرۆید",
    our_plan: "پلانی ئێمە",
    plan_1: "dolor sit amet consectetur",
    plan_2: "dolor sit amet consectetur",
    plan_3: "dolor sit amet consectetur",
    plan_4: "dolor sit amet consectetur",
    iqd: "دینار",
    month: "مانگانە",
    get_started: "ئێستا دەستپێبکە",
    footer_p:
      "A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.",
    usefull_links: "بەستەری خێرا",
    have_questions: "بۆ هەرپرسیار و پێشنییارێک ",
    copy_right: "مافی پارێزراوە بۆ تراکەر",
  },
};
